name = "relaycat-worker"
main = "src/index.ts"
compatibility_date = "2024-02-08"

[vars]
RELAYCAT_ENABLE_FORWARDING = "true"

[[d1_databases]]
binding = "DB"
database_name = "relaycat-db"
database_id = "1151ae69-4a98-477a-a5bd-7369fec4fc15"
